services:
  - type: web
    name: tech-tracker
    env: node
    region: frankfurt
    plan: free
    nodeVersion: 18.17.0 # <-- Явно задаем версию Node.js (совместимую с ES-модулями)
    buildCommand: npm run build # <-- Команда 'npm install' выполняется Render автоматически перед этим.
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: /api